# Copyright 2026 Boozt Fashion AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
---
services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ipam
      MYSQL_USER: ipam
      MYSQL_PASSWORD: ipam
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "ipam", "-pipam", "-e", "SELECT 1", "ipam"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    environment:
      IPAM_DATABASE_USER: ipam
      IPAM_DATABASE_PASSWORD: ipam
      IPAM_DATABASE_HOST: mysql:3306
      IPAM_DATABASE_NET: tcp
      IPAM_DATABASE_NAME: ipam
      IPAM_LOG_FORMAT: text
      OTEL_EXPORTER_OTLP_ENDPOINT: jaeger:4317
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686" # Jaeger UI
